=== DrStS/EVAA/xsd/InputSchemaEVAA.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:complexType name="setPerCorner_t">
		<xs:sequence>
			<xs:element name="RearRight" type="xs:decimal" />
			<xs:element name="RearLeft" type="xs:decimal" />
			<xs:element name="FrontLeft" type="xs:decimal" />
			<xs:element name="FrontRight" type="xs:decimal" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="EVAA_t">
		<xs:sequence>
			<xs:element name="Vehicle">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="TwoTrackModel">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Geometry">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="LateralReferenceToWheel"  type="setPerCorner_t" >
												</xs:element>
												<xs:element name="LongitudinalReferenceToWheel" type="setPerCorner_t" >
												</xs:element>
												<xs:element name="SuspensionSprings" type="setPerCorner_t" >
												</xs:element>
												<xs:element name="TireSprings" type="setPerCorner_t" >
												</xs:element>
											</xs:sequence>
											<xs:attribute name="referenceCoordinateSystem" type="xs:string" use="required" />
										</xs:complexType>
									</xs:element>
									<xs:element name="Stiffness">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="Tyre" type="setPerCorner_t" >
												</xs:element>
												<xs:element name="Body" type="setPerCorner_t" >
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
									<xs:element name="Mass">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="Body">
													<xs:complexType>
														<xs:attribute name="mass" type="xs:decimal" use="required" />
													</xs:complexType>
												</xs:element>
												<xs:element name="Tyre" type="setPerCorner_t">
												</xs:element>
												<xs:element name="UnsprungMass" type="setPerCorner_t">
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
									<xs:element name="Inertia">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="Body">
													<xs:complexType>
														<xs:sequence>
															<xs:element name="XX" type="xs:decimal" />
															<xs:element name="XY" type="xs:decimal" />
															<xs:element name="XZ" type="xs:decimal" />
															<xs:element name="YX" type="xs:decimal" />
															<xs:element name="YY" type="xs:decimal" />
															<xs:element name="YZ" type="xs:decimal" />
															<xs:element name="ZX" type="xs:decimal" />
															<xs:element name="ZY" type="xs:decimal" />
															<xs:element name="ZZ" type="xs:decimal" />
														</xs:sequence>
														<xs:attribute name="referenceCoordinateSystem" type="xs:string" use="required" />
													</xs:complexType>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="InputFileEVAA" type="EVAA_t"> </xs:element>
</xs:schema>

=== DrStS/EVAA/inputFiles/inputFileLinear.xml
<?xml version="1.0" encoding="utf-8"?>
<InputFileEVAA xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="InputSchemaEVAA.xsd">
    <Vehicle> 
		<TwoTrackModel>
			<Geometry referenceCoordinateSystem="CoG">
				<LateralReferenceToWheel>
					<RearRight>1.68</RearRight> 
					<RearLeft>1.68</RearLeft> 
					<FrontLeft>1.68</FrontLeft>
					<FrontRight>1.68</FrontRight>
				</LateralReferenceToWheel>
				<LongitudinalReferenceToWheel>
					<RearRight>1.596</RearRight> 
					<RearLeft>1.596</RearLeft> 
					<FrontLeft>1.395</FrontLeft>
					<FrontRight>1.395</FrontRight>
				</LongitudinalReferenceToWheel>
				<SuspensionSprings>
					<RearRight>0.2</RearRight> 
					<RearLeft>0.2</RearLeft> 
					<FrontLeft>0.2</FrontLeft>
					<FrontRight>0.2</FrontRight>
				</SuspensionSprings>
        		<TireSprings>
					<RearRight>0.2</RearRight> 
					<RearLeft>0.2</RearLeft> 
					<FrontLeft>0.2</FrontLeft>
					<FrontRight>0.2</FrontRight>
				</TireSprings>
			</Geometry>
			<Stiffness>
				<Tyre>
					<RearRight>260000.</RearRight> 
					<RearLeft>260000.</RearLeft> 
					<FrontLeft>260000.</FrontLeft>
					<FrontRight>260000.</FrontRight>
				</Tyre>
				<Body>
					<RearRight>16000.</RearRight> 
					<RearLeft>16000.</RearLeft> 
					<FrontLeft>16000.</FrontLeft>
					<FrontRight>16000.</FrontRight>
				</Body>
			</Stiffness>
			<Mass>
				<Body mass="1936.0" />
				<Tyre>
					<RearRight>30.</RearRight> 
					<RearLeft>30.</RearLeft> 
					<FrontLeft>30.</FrontLeft>
					<FrontRight>30.</FrontRight>
				</Tyre>
				<UnsprungMass>
					<RearRight>67.5</RearRight> 
					<RearLeft>67.5</RearLeft> 
					<FrontLeft>72.5</FrontLeft>
					<FrontRight>72.5</FrontRight>
				</UnsprungMass>
			</Mass>
			<Inertia>
				<Body referenceCoordinateSystem="CoG">
					<XX>640.</XX>
					<XY>0.</XY>
					<XZ>0.</XZ>
					<YX>0.</YX>
					<YY>0.</YY>
					<YZ>0.</YZ>
					<ZX>0.</ZX>
					<ZY>0.</ZY>
					<ZZ>4800.</ZZ>
				</Body>
			</Inertia>
		</TwoTrackModel>
	</Vehicle>
</InputFileEVAA>
